# Site
name: "Blockchain DevUx"
title: "Blockchain DevUx"
description: "Blockchain Study Group"
logo: 'assets/images/B DevUx-logo.png'
favicon: 'assets/images/logo.png'
baseurl: /study_group
# google_analytics: 'UA-46278016-1'
disqus: 'blockchain-devux'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mtdk1:
    name: Koichi Matsuda
    display_name: MTDK1
    gravatar: 67e9d06e2e91e94656692fee27768b2c
    # email: contactus@caldia.org
    web: https://mtdk1.github.io
    twitter: https://twitter.com/kouichi_matsuda
    description: ""
  mgr:
    name: manager
    avatar: assets/images/B DevUx-logo.png
    display_name: MGR
    web: https://bdevux.github.io


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-mermaid

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

# Jekyll mermaid
# https://github.com/jasonbellamy/jekyll-mermaid
mermaid:
  src: 'https://unpkg.com/mermaid@7.1.0/dist/mermaid.min.js'
